### ISSUE TITLE
Dependencies not clear

### ISSUE THREAD

**Issue by aaron404** [maxmindlin/scout-lang#2]
I am on Ubuntu 24.04 and after running the install script successfully I am unable to run scout because `libssl.so.1.1` is not missing. Can you list all the dependencies needed for a clean run in your docs?

**Comment by maxmindlin** [comment]
Hey thanks for the issue! Sorry about that - I'm far from an expert on Linux installs. 

Do you have access to cargo/rust on your ubuntu machine? I recently added a `cargo install` option and I'm wondering if that would resolve missing dependencies for you. I.e., `cargo install scoutlang`

**Comment by aaron404** [comment]
I tried `cargo install scoutlang` and hit the same issue. I double checked that I was running the new install and not my previous one as well. It looks like a manual install of `libssl.so.1.1` is required. See (here)[https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory]. Some of the comments suggest it is risky to install this older version of the lib so I prefer not to. I am not sure which of your dependencies requires this lib, but there might be an update that could solve this.

**Comment by PFWhite** [comment]
Could it be fantoccini? It supports using tls through rust via a feature flag which should obviate the problem. https://docs.rs/fantoccini/0.19.3/fantoccini/

I'm going to try building with that flag and seeing if that fixes it.

**Comment by maxmindlin** [comment]
> Could it be fantoccini? It supports using tls through rust via a feature flag which should obviate the problem. https://docs.rs/fantoccini/0.19.3/fantoccini/
> 
> 
> 
> I'm going to try building with that flag and seeing if that fixes it.

It likely is fantoccini. I'd happily accept a PR for a feature flag or something to build with rustls

**Comment by maxmindlin** [comment]
Realizing feature flags likely wouldnt work as this is a binary distribution. So will likely just need to set the feature flag for the library and just have rustls be the default behavior.
